

services:
  postgres:
    image: postgres:latest
    container_name: food_ordering_db
    environment:
      POSTGRES_DB: foodordering
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
